apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-deployment
  labels:
    app: prod-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: prod-nginx
  template:
    metadata:
      labels:
        app: prod-nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.27.3-perl
          ports:
            - containerPort: 80
                                                                                                                                                    
